-   id: format-yaml-launch-and-configs
    name: Format YAML launch and config files
    description: Format YAML launch and config files
    entry: launch-config-validator
    language: python
    files: \.(ya?ml)$
